
project_id = "hfdaowgithffhelybfve"

[api]
# No custom API configurations at the moment
port = 54321
schemes = ["http", "https"]
headers = []

[db]
# No custom database configurations

[functions]
[functions.create-wallets]
verify_jwt = true

