
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onojviswlkxuyfsksuhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ub2p2aXN3bGt4dXlmc2tzdWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNDA0ODAsImV4cCI6MjA1OTgxNjQ4MH0.nRHrwoKZsmH95950yWpuezfQKRwc8z4ofM7qmbuyPIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a single supabase client for interacting with your database
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  }
);

// Function to directly execute raw SQL queries
export const executeSql = async (query: string, params?: any[]) => {
  const { data, error } = await supabase.rpc('execute', { query, params });
  if (error) throw error;
  return data;
};
